### ISSUE TITLE
Real-world example would help

### ISSUE THREAD

**Issue by abhaybhargav** [node-casbin/mongoose-adapter#6]
Hi, thanks for this library. Appreciate the work

However, I have a request: 
It would be great if you could include a real-world example on how to use the library it in an app with Mongoose. Its very hard to figure that out from the current docs.  

Thanks

**Comment by Sefriol** [comment]
I am little unsure what you are looking for.

Example on how to use the adapter can be found in [readme](https://github.com/node-casbin/mongoose-adapter#getting-started).

Other examples on how to use adapter within an application like expressjs can be found [here](https://github.com/node-casbin/express-authz)
(And since the source code is really simple, you can just take inspiration from [it](https://github.com/node-casbin/express-authz/blob/master/authz.js)

**Comment by hsluoyz** [comment]
Closed as resolved.
